services:
  es:
    build:
      context: es
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  app:
    build:
      context: search-ufret
      dockerfile: Dockerfile
    environment:
      - ES_ENDPOINT=http://es:9200
    ports:
      - 8000:8000

volumes:
  es-data:

endpoints:
  labels:
    dev.okteto.com/generate-host: true
  rules:
    - path: /
      service: app
      port: 8000
