services:
  es:
    build:
      context: es
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300


volumes:
  es-data:

endpoints:
  labels:
    dev.okteto.com/endpoints: https://test-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
  rules:
    - path: /
      service: es
      port: 9200
